from tkinter import *
import funtions1 as ok
window = Tk()
window.geometry("360x600+50+50")
window.title("PHẦN MỀM TẤN CÔNG MẠNG WIFI")
label0 = Label(window, text="WIFI ATTACK", font=("Arial", 20), pady=20)
label0.pack(side=TOP)
labelFrame1 = LabelFrame(window, text="Select channel to attack", padx=20)
labelFrame1.pack(fill="both", expand="yes")
button1 = Button(labelFrame1, text=1, width=5, font=('Arial', 25), command=ok.attackChannel1)
button1.grid(column=0, row=0)
button2 = Button(labelFrame1, text=2, width=5, font=('Arial', 25), command=ok.attackChannel2)
button2.grid(column=1, row=0)
button3 = Button(labelFrame1, text=3, width=5, font=('Arial', 25), command=ok.attackChannel3)
button3.grid(column=2, row=0)
button4 = Button(labelFrame1, text=4, width=5, font=('Arial', 25), command=ok.attackChannel4)
button4.grid(column=0, row=1)
button5 = Button(labelFrame1, text=5, width=5, font=('Arial', 25), command=ok.attackChannel5)
button5.grid(column=1, row=1)
button6 = Button(labelFrame1, text=6, width=5, font=('Arial', 25), command=ok.attackChannel6)
button6.grid(column=2, row=1)
button7 = Button(labelFrame1, text=7, width=5, font=('Arial', 25), command=ok.attackChannel7)
button7.grid(column=0, row=2)
button8 = Button(labelFrame1, text=8, width=5, font=('Arial', 25), command=ok.attackChannel8)
button8.grid(column=1, row=2)
button9 = Button(labelFrame1, text=9, width=5, font=('Arial', 25), command=ok.attackChannel9)
button9.grid(column=2, row=2)
button10 = Button(labelFrame1, text=10, width=5, font=('Arial', 25), command=ok.attackChannel10)
button10.grid(column=0, row=3)
button11 = Button(labelFrame1, text=11, width=5, font=('Arial', 25), command=ok.attackChannel11)
button11.grid(column=1, row=3)
button12 = Button(labelFrame1, text=12, width=5, font=('Arial', 25), command=ok.attackChannel12)
button12.grid(column=2, row=3)
button13 = Button(labelFrame1, text=13, width=5, font=('Arial', 25), command=ok.attackChannel13)
button13.grid(column=0, row=4)
button14 = Button(labelFrame1, text=14, width=5, font=('Arial', 25), command=ok.attackChannel14)
button14.grid(column=1, row=4)
button15 = Button(labelFrame1, text="Close", width=5, font=('Arial', 25), command=window.destroy)
button15.grid(column=0, row=5, columnspan=3, sticky='ew')
label1 = Label(window, text="Van Bien Pro", font=("Algerian", 20))
label1.pack(side=BOTTOM)





window.mainloop()